### ISSUE TITLE
Delimiters in Arg2

### ISSUE THREAD

**Issue by prannayk** [pclubiitk/TechTests#10]
Assuming commands may be single line, out put may not be and can cause problems at the time of comparision!

Do I assume a given format according to my convenience or would the developers be willing to set a standard beforehand?

**Comment by pallavagarwal07** [comment]
Ideally, the output in the second file should contain the formatted `$ ./cmd1` type thingy before every output, where `./cmd1` is the command being executed.
The output should `ideally` end with a `%` if there is no newline at the end of output like zsh does (no extra points for this).
