### ISSUE TITLE
Clarification on docker/binary milestone

### ISSUE THREAD

**Issue by yashsriv** [pclubiitk/TechTests#4]
Can you please clarify what exactly needs to be done for the docker/binary thing? Is it going to be a docker container which is executed like  that or a binary which executes docker and then compares??

**Comment by pallavagarwal07** [comment]
This binary should work when put in any existing container, irrespective of whether the container has libraries or not

**Comment by pallavagarwal07** [comment]
The purpose is to create a wrapper to check the output of commands written by the user. The container to be used would depend on the topic the question is. For example, a question on python would require the use of a docker container with python installed.

@yashsriv Close the issue if your query is cleared

**Comment by yashsriv** [comment]
So lets say the arg1 is `gcc a.cpp`, then container will atleast contain gcc right??

**Comment by yashsriv** [comment]
Okay so it is confirmed that the docker container will be sufficiently equipped to run the commands in `arg1`
